### PR TITLE
Adding support for IPv4 Block resources

### PR DESCRIPTION
**Pull request by aaronmaxlevy**
Adding support for provisioning IPv4 Block resources

### CODE REVIEW

**Comment by adarobin** [comment]
Awesome @aaronmaxlevy ! This closes #2 and it's been on my radar for a bit but I've been too busy.

Any chance you'd be willing to add a simple acceptance test for this resource? Right now I only have a few tests for data sources, but getting one on this resource might shame me into getting them on the other resources 🙂

I don't have tests working with GitHub Actions yet, but I do have a non-prod environment I can manually run them against.

**Comment by aaronmaxlevy** [comment]
@adarobin Thanks for making the change to use a dedicated variable for the block parent ID — I had literally just figured out that was necessary and was about to push a commit to address that when I saw the email that you pushed a commit adding that.

I just pushed a commit removing the (now unnecessary / unused) reference to `testAccEntityDataSourceConfig` (since this now uses a dedicated variable instead)

**Comment by aaronmaxlevy** [comment]
@adarobin what is the error message you are getting?

**Comment by adarobin** [comment]
@aaronmaxlevy 

```
    resource_ip4_block_test.go:10: Step 1/1 error: Error running apply: exit status 1
        
        Error: Failed to create IP4 Block
        
          with bluecat_ip4_block.test,
          on terraform_plugin_test.tf line 16, in resource "bluecat_ip4_block" "test":
          16: resource "bluecat_ip4_block" "test" {
        
        "500 Server Error": "<?xml version='1.0' encoding='UTF-8'?><S:Envelope
        xmlns:S=\"http://schemas.xmlsoap.org/soap/envelope/\"><S:Body><S:Fault
        xmlns:ns4=\"http://www.w3.org/2003/05/soap-envelope\"><faultcode>S:Server</faultcode><faultstring>No
        block found or created in the selected
        range.</faultstring></S:Fault></S:Body></S:Envelope>"
--- FAIL: TestAccIP4BlockResource (0.62s)
```

**Comment by aaronmaxlevy** [comment]
@adarobin Thanks! So from what I can tell, this is most likely a permissions error. I tested manually calling the `getNextAvailableIPRange` SOAP API using a user with insufficient access to create a new block, and got the exact same error message. When I tried the exact same API call while authenticated with a user with sufficient access, it worked properly and returned an HTTP 200 response.

**Review by adarobin — APPROVED** [review]

**Comment by adarobin** [comment]
@aaronmaxlevy I just released [v0.5.0](https://github.com/umich-vci/terraform-provider-bluecat/releases/tag/v0.5.0) with this resource.  It should hit the Terraform Registry shortly if it hasn't already. 

I just discovered that the OpenTofu registry isn't updating (I don't see 0.4.5 there), so I will be addressing that shortly.

**Comment by aaronmaxlevy** [comment]
Thank you so much!

**Pull request merged**
